on:
  # Build the initial pull request
  pull_request:
    branches: [main]
  # Build the merge attempt with up tp date main branch
  merge_group:
    types: [checks_requested]
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "build"
        run: |
          sleep 20
          echo "$GITHUB_SHA"
          echo "$GITHUB_REF"
