on:
  pull_request:
jobs:
  build-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "build"
        run: |
          sleep 20
          echo "$GITHUB_SHA"
          echo "$GITHUB_REF"